dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: godigital-angular
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: mycart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: mycart-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: pim-product
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.8
- name: preview
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: subscription
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.27
- name: subscription-node-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
